[package]
name = "safe-cameroon-worker"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
dotenvy.workspace = true
safe-cameroon-application = { path = "../../crates/application" }
safe-cameroon-domain = { path = "../../crates/domain" }
safe-cameroon-infrastructure = { path = "../../crates/infrastructure" }
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
async-trait.workspace = true
