[package]
name = "safe-cameroon-infrastructure"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
aws-credential-types.workspace = true
aws-sigv4.workspace = true
hmac.workspace = true
http.workspace = true
safe-cameroon-application = { path = "../application" }
safe-cameroon-domain = { path = "../domain" }
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
