//! Self-service citizen subscriptions (prompts/11_CITIZEN_EXPERIENCE.md,
//! docs/MVP_FLOWS.md Flow 5). No authentication -- the caller is an
//! anonymous citizen, not a reviewer -- but every endpoint here other than
//! creation requires proving ownership via the `Management-Token` header
//! returned once at creation time (`crates/application/src/citizen_subscription.rs`).
//!
//! Only the Web Push channel is supported: it is the one channel a citizen
//! can self-subscribe to without a separate ownership-verification step,
//! since the subscription itself, generated by the browser, already proves
//! ownership (docs/OPEN_QUESTIONS.md -- WhatsApp/SMS provider and
//! verification approach are still undecided). Reviewer-managed
//! subscriptions (`subscriptions.rs`) are unaffected and can still use any
//! channel and any visibility.

use axum::{
    Json,
    extract::{Path, State},
    http::{HeaderMap, StatusCode},
};
use safe_cameroon_application::case_workflow::Actor;
use safe_cameroon_application::citizen_subscription::{
    CitizenSubscriptionError, CitizenSubscriptionRequest, prepare_citizen_subscription,
    verify_management_token,
};
use safe_cameroon_application::rate_limit::RateLimitScope;
use safe_cameroon_domain::{
    ChannelEndpoint, ChannelType, Comparison, DeliveryPreference, DeliveryStrategy, GeoArea,
    IncidentType, Severity, Subscription, SubscriptionId, SubscriptionRule,
};
use safe_cameroon_infrastructure::postgres::SubscriptionUpdateOutcome;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::error::ApiError;
use crate::rate_limit::enforce_rate_limit;
use crate::request_id::request_id_from_headers;
use crate::source_key::source_key_from_headers;
use crate::state::AppState;

const MANAGEMENT_TOKEN_HEADER: &str = "Management-Token";

fn not_found(request_id: Uuid) -> ApiError {
    ApiError {
        status: StatusCode::NOT_FOUND,
        code: "CITIZEN_SUBSCRIPTION_NOT_FOUND",
        // Deliberately the same response whether the id doesn't exist, the
        // consumer behind it isn't self-service, the token header is
        // missing, or the token is wrong -- distinguishing any of those
        // would let a caller enumerate valid subscription ids.
        message: "No citizen subscription exists with that id and management token.",
        request_id,
    }
}

fn persistence_failed(request_id: Uuid) -> ApiError {
    ApiError {
        status: StatusCode::INTERNAL_SERVER_ERROR,
        code: "SUBSCRIPTION_PERSISTENCE_FAILED",
        message: "The request could not be saved. Please try again.",
        request_id,
    }
}

fn invalid_request(error: CitizenSubscriptionError, request_id: Uuid) -> ApiError {
    let code = match error {
        CitizenSubscriptionError::EmptyIncidentTypes => "EMPTY_INCIDENT_TYPES",
        CitizenSubscriptionError::InvalidGeography => "INVALID_GEOGRAPHY_AREA",
        CitizenSubscriptionError::InvalidPushSubscription => "INVALID_PUSH_SUBSCRIPTION",
    };
    let message = match error {
        CitizenSubscriptionError::EmptyIncidentTypes => "At least one incident type is required.",
        CitizenSubscriptionError::InvalidGeography => "geography cannot be blank.",
        CitizenSubscriptionError::InvalidPushSubscription => "push_subscription is invalid.",
    };
    ApiError {
        status: StatusCode::BAD_REQUEST,
        code,
        message,
        request_id,
    }
}

/// Mirrors a browser's `PushSubscription.toJSON()` shape exactly
/// (`{endpoint, keys: {p256dh, auth}}`). Kept independent of the `web-push`
/// crate's own `SubscriptionInfo` type so this API layer never depends on a
/// specific channel provider's crate (a channel is not a provider).
#[derive(Deserialize, Serialize)]
pub struct PushSubscriptionInput {
    endpoint: String,
    keys: PushSubscriptionKeys,
}

#[derive(Deserialize, Serialize)]
pub struct PushSubscriptionKeys {
    p256dh: String,
    auth: String,
}

#[derive(Deserialize)]
pub struct CreateCitizenSubscriptionRequest {
    incident_types: Vec<IncidentType>,
    minimum_severity: Severity,
    geography: String,
    push_subscription: PushSubscriptionInput,
}

#[derive(Serialize)]
pub struct CreateCitizenSubscriptionResponse {
    consumer_id: Uuid,
    subscription_id: Uuid,
    management_token: String,
}

pub async fn create_citizen_subscription(
    State(state): State<AppState>,
    headers: HeaderMap,
    Json(request): Json<CreateCitizenSubscriptionRequest>,
) -> Result<(StatusCode, Json<CreateCitizenSubscriptionResponse>), ApiError> {
    let request_id = request_id_from_headers(&headers);
    enforce_rate_limit(
        state.rate_limiter.as_ref(),
        RateLimitScope::CitizenSubscriptionCreation,
        source_key_from_headers(&headers),
        request_id,
    )
    .await?;

    let push_subscription_json = serde_json::to_string(&request.push_subscription)
        .expect("PushSubscriptionInput of plain strings always serializes");

    let prepared = prepare_citizen_subscription(CitizenSubscriptionRequest {
        incident_types: request.incident_types,
        minimum_severity: request.minimum_severity,
        geography: request.geography,
        push_subscription_json,
    })
    .map_err(|error| invalid_request(error, request_id))?;

    state
        .consumers
        .create_with_management_token(&prepared.consumer, &prepared.management_token_hash)
        .await
        .map_err(|_| persistence_failed(request_id))?;
    state
        .delivery_preferences
        .upsert(prepared.consumer.id(), &prepared.delivery_preference)
        .await
        .map_err(|_| persistence_failed(request_id))?;
    state
        .subscriptions
        .create(&prepared.subscription)
        .await
        .map_err(|_| persistence_failed(request_id))?;

    Ok((
        StatusCode::CREATED,
        Json(CreateCitizenSubscriptionResponse {
            consumer_id: prepared.consumer.id().as_uuid(),
            subscription_id: prepared.subscription.id().as_uuid(),
            management_token: prepared.management_token,
        }),
    ))
}

/// Loads the subscription for `subscription_id` and checks the
/// `Management-Token` header against its consumer's stored hash. Returns the
/// same [`not_found`] error for every failure mode (see that function's
/// comment) so a caller can never distinguish "wrong token" from "no such
/// subscription".
async fn authorize_citizen_subscription(
    state: &AppState,
    subscription_id: SubscriptionId,
    headers: &HeaderMap,
    request_id: Uuid,
) -> Result<Subscription, ApiError> {
    let subscription = state
        .subscriptions
        .find_by_id(subscription_id)
        .await
        .map_err(|_| persistence_failed(request_id))?
        .ok_or_else(|| not_found(request_id))?;

    let presented_token = headers
        .get(MANAGEMENT_TOKEN_HEADER)
        .and_then(|value| value.to_str().ok())
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .ok_or_else(|| not_found(request_id))?;

    let stored_hash = state
        .consumers
        .management_token_hash(subscription.consumer_id())
        .await
        .map_err(|_| persistence_failed(request_id))?
        .ok_or_else(|| not_found(request_id))?;

    if verify_management_token(presented_token, &stored_hash) {
        Ok(subscription)
    } else {
        Err(not_found(request_id))
    }
}

#[derive(Serialize)]
pub struct CitizenSubscriptionRulesResponse {
    incident_types: Vec<IncidentType>,
    minimum_severity: Severity,
    geography: String,
}

fn rules_response(subscription: &Subscription) -> CitizenSubscriptionRulesResponse {
    let mut incident_types = Vec::new();
    let mut minimum_severity = Severity::Low;
    let mut geography = String::new();
    for rule in subscription.rules() {
        match rule {
            SubscriptionRule::IncidentType(values) => incident_types = values.clone(),
            SubscriptionRule::Severity { value, .. } => minimum_severity = *value,
            SubscriptionRule::Geography(area) => geography = area.as_str().to_owned(),
            SubscriptionRule::EventType(_) | SubscriptionRule::Visibility(_) => {}
        }
    }
    CitizenSubscriptionRulesResponse {
        incident_types,
        minimum_severity,
        geography,
    }
}

pub async fn get_citizen_subscription(
    State(state): State<AppState>,
    Path(subscription_id): Path<Uuid>,
    headers: HeaderMap,
) -> Result<Json<CitizenSubscriptionRulesResponse>, ApiError> {
    let request_id = request_id_from_headers(&headers);
    let subscription = authorize_citizen_subscription(
        &state,
        SubscriptionId::from_uuid(subscription_id),
        &headers,
        request_id,
    )
    .await?;
    Ok(Json(rules_response(&subscription)))
}

#[derive(Deserialize)]
pub struct UpdateCitizenSubscriptionRequest {
    incident_types: Vec<IncidentType>,
    minimum_severity: Severity,
    geography: String,
    push_subscription: Option<PushSubscriptionInput>,
}

pub async fn update_citizen_subscription(
    State(state): State<AppState>,
    Path(subscription_id): Path<Uuid>,
    headers: HeaderMap,
    Json(request): Json<UpdateCitizenSubscriptionRequest>,
) -> Result<Json<CitizenSubscriptionRulesResponse>, ApiError> {
    let request_id = request_id_from_headers(&headers);
    let mut subscription = authorize_citizen_subscription(
        &state,
        SubscriptionId::from_uuid(subscription_id),
        &headers,
        request_id,
    )
    .await?;

    if request.incident_types.is_empty() {
        return Err(invalid_request(
            CitizenSubscriptionError::EmptyIncidentTypes,
            request_id,
        ));
    }
    let geo_area = GeoArea::new(request.geography)
        .map_err(|_| invalid_request(CitizenSubscriptionError::InvalidGeography, request_id))?;

    let rules = vec![
        SubscriptionRule::IncidentType(request.incident_types),
        SubscriptionRule::Severity {
            operator: Comparison::GreaterThanOrEqual,
            value: request.minimum_severity,
        },
        SubscriptionRule::Geography(geo_area),
        SubscriptionRule::Visibility(
            safe_cameroon_application::citizen_subscription::CITIZEN_ALERT_VISIBILITIES.to_vec(),
        ),
    ];
    subscription
        .update_rules(rules)
        .expect("rules is never empty: it always includes the incident-type rule");

    let outcome = state
        .subscriptions
        // No reviewer is involved in a citizen's own update -- this mirrors
        // reports.rs's unauthenticated writes, which are also attributed to
        // Actor::Automated rather than a real reviewer identity.
        .update(&subscription, Actor::Automated, request_id)
        .await
        .map_err(|_| persistence_failed(request_id))?;
    if outcome == SubscriptionUpdateOutcome::Conflict {
        return Err(ApiError {
            status: StatusCode::CONFLICT,
            code: "SUBSCRIPTION_VERSION_CONFLICT",
            message: "This subscription changed since it was last read. Please retry.",
            request_id,
        });
    }

    if let Some(push_subscription) = request.push_subscription {
        let address = serde_json::to_string(&push_subscription)
            .expect("PushSubscriptionInput of plain strings always serializes");
        let endpoint = ChannelEndpoint::new(ChannelType::Push, address).map_err(|_| {
            invalid_request(
                CitizenSubscriptionError::InvalidPushSubscription,
                request_id,
            )
        })?;
        let preference = DeliveryPreference::new(DeliveryStrategy::All, vec![endpoint])
            .expect("exactly one channel is never empty or duplicated");
        state
            .delivery_preferences
            .upsert(subscription.consumer_id(), &preference)
            .await
            .map_err(|_| persistence_failed(request_id))?;
    }

    Ok(Json(rules_response(&subscription)))
}

pub async fn cancel_citizen_subscription(
    State(state): State<AppState>,
    Path(subscription_id): Path<Uuid>,
    headers: HeaderMap,
) -> Result<StatusCode, ApiError> {
    let request_id = request_id_from_headers(&headers);
    let subscription = authorize_citizen_subscription(
        &state,
        SubscriptionId::from_uuid(subscription_id),
        &headers,
        request_id,
    )
    .await?;

    state
        .subscriptions
        .delete(subscription.id())
        .await
        .map_err(|_| persistence_failed(request_id))?;

    Ok(StatusCode::NO_CONTENT)
}
