//! Web Push (VAPID) adapter -- unlike the other channels in this module,
//! this one is real (not mock/sandbox): it actually delivers to a browser's
//! push subscription. Chosen as the first real channel specifically because
//! it needs no vendor account, no per-message cost, and no separate
//! ownership-verification step (the subscription itself, generated by the
//! browser, *is* the proof of ownership) -- unlike WhatsApp/SMS, whose
//! provider and verification approach are still open questions
//! (docs/OPEN_QUESTIONS.md).

use async_trait::async_trait;
use safe_cameroon_application::channel::{
    Channel, ChannelError, ChannelSendOutcome, EndpointValidationError, OutboundMessage,
};
use safe_cameroon_domain::ChannelType;
use web_push::request_builder::build_request;
use web_push::{ContentEncoding, SubscriptionInfo, VapidSignatureBuilder, WebPushMessageBuilder};

/// A [`ChannelEndpoint`](safe_cameroon_domain::ChannelEndpoint) address for
/// [`ChannelType::Push`] is the JSON-serialized form of the browser's
/// `PushSubscription` object (`{endpoint, keys: {p256dh, auth}}`), matching
/// `web_push::SubscriptionInfo`'s own `Deserialize` shape directly.
fn parse_subscription(address: &str) -> Option<SubscriptionInfo> {
    serde_json::from_str(address).ok()
}

pub struct WebPushChannel {
    vapid_private_key_pem: Vec<u8>,
    subject: String,
    http_client: reqwest::Client,
}

impl WebPushChannel {
    pub fn new(vapid_private_key_pem: Vec<u8>, subject: impl Into<String>) -> Self {
        Self {
            vapid_private_key_pem,
            subject: subject.into(),
            http_client: reqwest::Client::new(),
        }
    }
}

#[async_trait]
impl Channel for WebPushChannel {
    fn channel_type(&self) -> ChannelType {
        ChannelType::Push
    }

    fn validate_endpoint(&self, endpoint_address: &str) -> Result<(), EndpointValidationError> {
        if parse_subscription(endpoint_address).is_some() {
            Ok(())
        } else {
            Err(EndpointValidationError {
                channel: ChannelType::Push,
                reason: "expected a serialized browser PushSubscription \
                    ({\"endpoint\":..,\"keys\":{\"p256dh\":..,\"auth\":..}})"
                    .into(),
            })
        }
    }

    async fn send(&self, message: OutboundMessage) -> Result<ChannelSendOutcome, ChannelError> {
        let subscription =
            parse_subscription(&message.endpoint_address).ok_or_else(|| ChannelError {
                retryable: false,
                message: "Push: endpoint_address is not a valid push subscription".into(),
            })?;

        let mut sig_builder =
            VapidSignatureBuilder::from_pem(self.vapid_private_key_pem.as_slice(), &subscription)
                .map_err(|error| ChannelError {
                retryable: false,
                message: format!("Push: invalid VAPID key: {error}"),
            })?;
        sig_builder.add_claim("sub", self.subject.as_str());

        let signature = sig_builder.build().map_err(|error| ChannelError {
            retryable: false,
            message: format!("Push: VAPID signing failed: {error}"),
        })?;

        let mut builder = WebPushMessageBuilder::new(&subscription);
        builder.set_payload(ContentEncoding::Aes128Gcm, message.body.as_bytes());
        builder.set_vapid_signature(signature);
        let push_message = builder.build().map_err(|error| ChannelError {
            retryable: false,
            message: format!("Push: message build failed: {error}"),
        })?;

        // build_request always issues a POST (the Web Push protocol only
        // ever POSTs to the subscription's own endpoint), so there is no
        // method to translate between the crate's http 0.2 Request and this
        // workspace's reqwest (http 1.x) -- only the URI, headers, and body
        // need copying across.
        let request = build_request::<Vec<u8>>(push_message);
        let (parts, body) = request.into_parts();
        let mut outgoing = self.http_client.post(parts.uri.to_string());
        for (name, value) in parts.headers.iter() {
            outgoing = outgoing.header(name.as_str(), value.as_bytes());
        }

        let response = outgoing
            .body(body)
            .send()
            .await
            .map_err(|error| ChannelError {
                retryable: true,
                message: format!("Push: request failed: {error}"),
            })?;

        let status = response.status();
        if status.is_success() {
            Ok(ChannelSendOutcome {
                provider_message_id: None,
            })
        } else if status.as_u16() == 404 || status.as_u16() == 410 {
            // The browser revoked or expired the subscription -- retrying
            // the same endpoint can never succeed.
            Err(ChannelError {
                retryable: false,
                message: format!("Push: subscription no longer valid ({status})"),
            })
        } else if status.is_server_error() || status.as_u16() == 429 {
            Err(ChannelError {
                retryable: true,
                message: format!("Push: provider error ({status})"),
            })
        } else {
            Err(ChannelError {
                retryable: false,
                message: format!("Push: rejected ({status})"),
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEST_ADDRESS: &str = r#"{"endpoint":"https://push.example/abc","keys":{"p256dh":"BGa4N1PI79lboMR_YrwCiCsgp35DRvedt7opHcf0yM3iOBTSoQYqQLwWxAfRKE6tsDnReWmhsImkhDF_DBdkNSU","auth":"EvcWjEgzr4rbvhfi3yds0A"}}"#;

    fn test_channel() -> WebPushChannel {
        let output = std::process::Command::new("openssl")
            .args(["ecparam", "-name", "prime256v1", "-genkey", "-noout"])
            .output()
            .expect("openssl must be available to generate a test VAPID key");
        assert!(output.status.success(), "openssl keygen failed");
        WebPushChannel::new(output.stdout, "mailto:test@example.com")
    }

    #[test]
    fn accepts_a_well_formed_subscription() {
        assert!(test_channel().validate_endpoint(TEST_ADDRESS).is_ok());
    }

    #[test]
    fn rejects_anything_that_is_not_a_push_subscription() {
        let error = test_channel().validate_endpoint("not json").unwrap_err();
        assert_eq!(error.channel, ChannelType::Push);
    }

    #[tokio::test]
    async fn send_fails_fast_with_a_non_retryable_error_for_a_malformed_address() {
        let error = test_channel()
            .send(OutboundMessage {
                endpoint_address: "not json".into(),
                body: "hello".into(),
            })
            .await
            .unwrap_err();
        assert!(!error.retryable);
    }
}
