[package]
name = "safe-cameroon-api"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
safe-cameroon-application = { path = "../../crates/application" }
safe-cameroon-domain = { path = "../../crates/domain" }
safe-cameroon-infrastructure = { path = "../../crates/infrastructure" }
serde.workspace = true
sqlx.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
hmac.workspace = true
serde_json.workspace = true
sha2.workspace = true
tower.workspace = true
